# Generated by Django 4.1.3 on 2023-06-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_college_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
