# Generated by Django 4.1.3 on 2023-06-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
