# Generated by Django 4.1.3 on 2023-06-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_alter_form_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
