# Generated by Django 4.1.3 on 2023-06-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_alter_form_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='course',
        ),
        migrations.RemoveField(
            model_name='form',
            name='department',
        ),
        migrations.RemoveField(
            model_name='form',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='form',
            name='purpose',
        ),
    ]
