# Generated by Django 4.1.3 on 2023-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_remove_form_course_remove_form_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
                ('materials', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='form',
        ),
    ]
