# Generated by Django 4.1.3 on 2023-06-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0014_application_delete_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
