# Generated by Django 4.1.3 on 2023-06-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0017_alter_application_gender_alter_application_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(max_length=200),
        ),
    ]
